DROP TABLE IF EXISTS `course`;
CREATE TABLE `course` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSERT_DATETIME` datetime DEFAULT NULL,
  `UPDATE_DATETIME` datetime DEFAULT NULL,
  `COURSE_NAME` varchar(255) DEFAULT NULL,
  `COURSE_TYPE_ID` int(11) DEFAULT 0,
  `COURSE_VIDEO_KEY` varchar(255) DEFAULT NULL,
  `COURSE_REMARK` varchar(1000) DEFAULT NULL,
  `UPLOAD_USER_ID` int(11) DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DELIMITER ;;
CREATE TRIGGER `COURSE_INSERT` BEFORE INSERT ON `course` FOR EACH ROW SET NEW.INSERT_DATETIME = NOW(), NEW.UPDATE_DATETIME = NOW();;;
DELIMITER ;
DELIMITER ;;
CREATE TRIGGER `COURSE_UPDATE` BEFORE UPDATE ON `course` FOR EACH ROW SET NEW.UPDATE_DATETIME = NOW();;;
DELIMITER ;

DROP TABLE IF EXISTS `course_type`;
CREATE TABLE `course_type` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COURSE_TYPE_NAME` varchar(255) DEFAULT NULL,
  `PARENT_COURSE_TYPE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
